### ISSUE TITLE
(In)compatibility with certain ro-crate-metadata.json file

### ISSUE THREAD

**Issue by gcapes** [UTS-eResearch/ro-crate-html-js#24]
I'm new to RO crates and have installed ro-crate-html-js, trying to build an html preview page.

I have had success with a [minimal `ro-crate-metadata.json` example](https://www.researchobject.org/ro-crate/1.1/root-data-entity.html#minimal-example-of-ro-crate), but I get errors when trying a [different file](https://github.com/openphacts/ops-linksets/blob/main/ro-crate-metadata.json) @stain , which I believe was previously build without issue using your tool.

```
$ node_modules/.bin/rochtml ro-crate-metadata.json 
(node:32185) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ROCrate.__addToContextLookup (/home/mbexegc2/projects/esciencelab/rocrate-to-pages/node_modules/ro-crate/lib/rocrate.js:403:30)
    at ROCrate.resolveContext (/home/mbexegc2/projects/esciencelab/rocrate-to-pages/node_modules/ro-crate/lib/rocrate.js:398:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:32185) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32185) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:32185) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ROCrate.__addToContextLookup (/home/mbexegc2/projects/esciencelab/rocrate-to-pages/node_modules/ro-crate/lib/rocrate.js:403:30)
    at ROCrate.resolveContext (/home/mbexegc2/projects/esciencelab/rocrate-to-pages/node_modules/ro-crate/lib/rocrate.js:398:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:32185) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Would you be able to look into this?

Thanks!

**Comment by ptsefton** [comment]
You can get this working if you remove     "https://schema.org/" from line 4 of the source file (it should not be needed, as the RO-Crate context has Schema.org in it anyway - I think Schema.org changed the way they serve the context file so this no longer works (is that right @stain?). The code should not be dying like this, though so I will ask @alvinsw to look at this issue and make sure that we fix it.

Note that development on this is now taking place over at https://github.com/Arkisto-Platform/ro-crate-html-js - we need to make sure the RO-Crate site is pointing to the right pkace.

@simon-kruik  - would you be able to put a notice on the UTS repositories to say that they have moved?

**Comment by simon-kruik** [comment]
> @simon-kruik - would you be able to put a notice on the UTS repositories to say that they have moved?

Pull request #25 has been created for this repo with an updated README. Did you also want a similar notice on https://github.com/UTS-eResearch/ro-crate-js and https://github.com/UTS-eResearch/ro-crate-excel?

**Comment by gcapes** [comment]
Thanks for your quick replies!

**Comment by ptsefton** [comment]
Yes please @simon-kruik
